services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: ["sh", "./docker-entrypoint.sh"]
    networks:
      - web-network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  web-network:
